version: '3.8'

services:
  event-service:
    build: ./services/event-service
    ports:
      - "3001:3001"
    volumes:
      - ./lottix-app/src/data:/app/data
    environment:
      - NODE_ENV=production

  signup-service:
    build: ./services/signup-service
    ports:
      - "3002:3002"
    volumes:
      - ./lottix-app/src/data:/app/data
    environment:
      - NODE_ENV=production

volumes:
  data:
