# This is a docker compose file for defining and running
# multi-container environments. It simplifies the control
# of your application stack into a single configuration
# file. The following commands are useful:
#
#   docker compose up          - "runs" the entire system
#   docker compose up --build  - force a build and "runs" system
#   docker compose up -d       - "runs" system in detacted mode
#   docker compose down        - "closes" the entire system and deletes everything
#   docker compose stop        - stop running containers without removing them
#   docker compose start       - start previously stopped containers
#
version: '3.9'
name: ms-arch

services:
  registry:
    build:
      context: ./registry
    container_name: registry
    networks:
      - skynet

  concert-service:
    build:
      context: ./concert-service
    container_name: concert-service
    depends_on:
      - registry
    networks:
      - skynet 
    volumes:
      - ./data:/app/data

  users-service:
    build:
      context: ./users-service
    container_name: users-service
    depends_on:
      - registry
    networks:
      - skynet
    volumes:
      - ./data:/app/data

  user-fetch-service:
    build:
      context: ./user-fetch-service
    container_name: user-fetch-service
    depends_on:
      - registry
    networks:
      - skynet
    volumes:
      - ./data:/app/data  

  concert-fetch-service:
    build:
      context: ./concert-fetch-service
    container_name: concert-fetch-service
    depends_on:
      - registry
    networks:
      - skynet
    volumes:
      - ./data:/app/data  

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - concert-service
    networks:
      - skynet
    ports:
      - "3000:3000"

networks:
  skynet:
    driver: bridge

